### PR TITLE
Fix DoS Bug

### LINKED ISSUE #2: DoS due to lack of sanitation
This bug carries over from previous versions of ModChat, as well as all of the forks of that version, and can be fixed in a similar way.

When receiving socket.io messages, the server does not check to make sure that requested properties are found in the data object, and therefore, errors may be thrown during this, crashing the server.

While the socket is private, and I cannot personally find out how to forge a request to send a message given a token, it still can be used for this DoS system.

Simply copy the socket.io-client code from https://github.com/socketio/socket.io-client/blob/master/dist/socket.io.min.js and then type in the following code:
```js
io(serverHost).emit("chat")
```

Once you do this, ModChat's server will crash.

### LINKED ISSUE #3: Arbitrary join messages
Same as in #2 for getting access to the socket.

However, this bug allows you to put in any user for the join message, as shown below:
image

This is achieved by first gaining access to the socket.

Then, you must authenticate using this code:
```js
let that = {user:{name:JSON.parse(localStorage.getItem("user")).name
, password:JSON.parse(localStorage.getItem("user")).password,token:JSON.parse(localStorage.getItem("user")).token
}, currentRoom: "general"};
    socket.on("connect", () => {
      console.log('Connected to server');
      socket.emit('authentication', {
        username: that.user.name,
        password: that.user.password
      });
      console.log('Submitted auth');
      socket.on('authenticated', function() {
        console.log('Successfully authed');
        socket.emit("joinRoom", {
          "username": that.user.name,
          "roomname": that.currentRoom
        });
      });
    });
```

Then use this to connect the socket:
```js
socket.connect();
```

Now that the socket is connected, all you have to do is use a `socket.emit` message.
```js
socket.emit("joinRoom", {username:"amazingmech2418 hacked ModChat and ", roomname:"general"})
```

Another issue is that this essentially enables anonymous messaging and also, the ModChat Bot's messages are not filtered, allowing filter bypass without a way to know who to ban. 

Luckily though, this cannot be used for XSS.

### PR DESCRIPTION
**Pull request by AmazingMech2418**
Fixes #2 

I need to work on getting this to work for #3 as well, but that must come after `getCurrentUser` is fixed, since it seems that it attempts to use a synchronous method with an asynchronous function, and therefore will return `undefined` every time.

### CODE REVIEW

**Comment by micahlt** [comment]
I see - would you rather fix #3 before I merge this?

**Comment by AmazingMech2418** [comment]
Well, #3 would require the `getCurrentUser` function to be fixed and I'm still not very familiar with NeDB.

**Comment by AmazingMech2418** [comment]
By the way, I'm logged in as you on ModChat right now. XD Might want to move users.db to the gitignore...

**Comment by AmazingMech2418** [comment]
image

**Comment by micahlt** [comment]
Deleted the database file 😋 Interesting... so you're saying that the issue is an async function?  [Here ](https://github.com/louischatriot/nedb#readme)are the NeDB docs - I don't see anything about async functions there.

**Comment by micahlt** [comment]
Also can you get on Modchat right now?  At https://modchat.micahlindley.com/ of course.

**Comment by AmazingMech2418** [comment]
Well, it uses a callback, so if you try to return a variable set by the callback, it will just return undefined.

**Comment by micahlt** [comment]
But if you look at [this line](https://github.com/micahlt/modchat-server/blob/ff6f781fc1e21af05b85fee925bd9ace9ad69e5f/user.js#L31) I set the toReturn variable outside of the database function...

**Comment by AmazingMech2418** [comment]
It is declared, but not initialized. When it returns, it returns the value at that point, which is still undefined.

**Comment by micahlt** [comment]
Resolved in d60c6ecacad7e4dfac07fc29ef7ef8d4e09ff82f.

**Pull request closed without merging**
